---
- name: "unarchive backend files"
  unarchive:
    src: api.tar.gz
    dest: /home/ubuntu/

- name: "check folder backend"
  command: |
    ls -al /home/ubuntu/backend/
  register: output_check
  debug:
    var: output_check.stdout_lines

- name: "executing node"
  command: |
    cd /home/ubuntu/backend/dist/
    npm install
    pm2 stop default
    pm2 start npm --name 'udapeople' -- start
    pm2 ls