---
- name: "unarchive backend files"
  unarchive:
    src: api.tar.gz
    dest: /home/ubuntu/

- name: "executing node"
  command: |
    pm2 start npm --name 'udapeople' -- start
  register: cmd_output
  args:
    chdir: /home/ubuntu/backend/

- debug:
    var: cmd_output